services:
  data-commons-mcp:
    build: .
    # image: ghcr.io/eosc-data-commons/data-commons-mcp:main
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - OPENSEARCH_URL=http://opensearch:9200
    env_file:
      - keys.env
    volumes:
      - ./data:/data # For logs
